spring.application.name=paymentGateway

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/razorpayData
spring.datasource.username=root
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Razorpay Configuration
razorpay.key.id=rzp_test_TLYdnocq1Qjz6G
razorpay.key.secret=ZmI6dIQ46W6KAShZSSgruX2N


# EMAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=your_email
spring.mail.password=your_app_password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true



# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Spring Boot Admin
spring.boot.admin.client.url=http://localhost:1111
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
