spring.application.name=MovieBookingApplication

server.port=9090


# EUREKA CLIENT CONFIGURATION
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/




# ADMIN CLIENT CONFIGURATION
spring.boot.admin.client.url=http://localhost:1111
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true



# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/movie_booking_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Rizwankhan@123#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT CONFIGURATION
jwt.secret=c2VjcmV0S2V5Rm9yTW92aWVCb29raW5nQXBwbGljYXRpb25TZWN1cml0eUoyNTY=
jwt.expiration=86400000

# Admin Secret Key for register user with Role Admin
admin.secret.key=MovieBookingAppAdminSecretKey9988
