server.port=3333
spring.application.name=API-GATEWAY

# Eureka Server, Admin Server, Actuator Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.boot.admin.client.url=http://localhost:1111
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.cloud.gateway.routes[0].id=movie
spring.cloud.gateway.routes[0].uri=lb://MOVIEBOOKINGAPPLICATION
spring.cloud.gateway.routes[0].predicates[0]=Path=/movie/**,/booking/**,/show/**,/screen/**,/seat/**,/show-seat/**,/theater/**,/auth/**

spring.cloud.gateway.routes[1].id=Notification
spring.cloud.gateway.routes[1].uri=lb://EMAILNOTIFICATIONSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/notification/**

spring.cloud.gateway.routes[2].id=payment
spring.cloud.gateway.routes[2].uri=lb://PAYMENTGATEWAY
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/payment/**

# GLOBAL CORS CONFIGURATION
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
